// <auto-generated />
using System;
using Gui_end;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gui_end.Migrations
{
    [DbContext(typeof(SignUpDbConnect))]
    [Migration("20250222101624_InitialCreate5")]
    partial class InitialCreate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Gui_end.DbConnect", b =>
                {
                    b.Property<int>("StudentIdFORSMS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNo1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("seatNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("time")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentIdFORSMS");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
